// <auto-generated />
using System;
using FlowUp.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlowUp.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260809234814_AtualizarNomesContributor")]
    partial class AtualizarNomesContributor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FlowUp.Api.Models.ContributorWorkshop", b =>
                {
                    b.Property<int>("ContributorId")
                        .HasColumnType("int")
                        .HasColumnName("contributor_id");

                    b.Property<int>("WorkshopId")
                        .HasColumnType("int")
                        .HasColumnName("workshop_id");

                    b.HasKey("ContributorId", "WorkshopId");

                    b.HasIndex("WorkshopId");

                    b.ToTable("Contributor_Workshop", (string)null);
                });

            modelBuilder.Entity("FlowUp.Api.Models.Contributors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_contributor");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name_contributor");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("last_name_contributor");

                    b.HasKey("Id");

                    b.ToTable("Contributor", (string)null);
                });

            modelBuilder.Entity("FlowUp.Api.Models.Workshops", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_workshop");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_workshop");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description_workshop");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name_workshop");

                    b.HasKey("Id");

                    b.ToTable("Workshop", (string)null);
                });

            modelBuilder.Entity("FlowUp.Api.Models.ContributorWorkshop", b =>
                {
                    b.HasOne("FlowUp.Api.Models.Contributors", "Contributor")
                        .WithMany("ContributorWorkshops")
                        .HasForeignKey("ContributorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlowUp.Api.Models.Workshops", "Workshop")
                        .WithMany("ContributorWorkshops")
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contributor");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("FlowUp.Api.Models.Contributors", b =>
                {
                    b.Navigation("ContributorWorkshops");
                });

            modelBuilder.Entity("FlowUp.Api.Models.Workshops", b =>
                {
                    b.Navigation("ContributorWorkshops");
                });
#pragma warning restore 612, 618
        }
    }
}
